version: "2"
checks:
  method-lines:
    config:
      threshold: 50
exclude_patterns:
  - "AutomatedTests/"
  - "**/*.js"
  - ".mvn/"
  - ".github/"
  - ".env"
  - ".env.template"
  - "jag-staffnet-biometrics-application/src/test"
  - "jag-staffnet-identity-provisioning-application/src/test"
