security:
  basic-auth:
    password: ${BASIC_AUTH_PASS}
    username: ${BASIC_AUTH_USER}
server:
  port: 8081

test:
  password: ${BASIC_AUTH_PASS}
  username: ${BASIC_AUTH_USER}
  api-host-identity: ${API_HOST_IDENTITY}
  api-host-biometrics: ${API_HOST_BIOMETRICS}

