security:
  basic-auth:
    password: ${PROVISION_AUTH_PASS}
    username: ${PROVISION_AUTH_USER}
staffnet:
  host: ${ORDS_HOST}
management:
  endpoints:
    web:
      exposure:
        include: metrics,prometheus,health

