security:
  basic-auth:
    password: ${BASIC_AUTH_PASS:test-password}
    username: ${BASIC_AUTH_USER:test-user}
  web-service:
    password: ${BASIC_AUTH_PASS:test-password}
    username: ${BASIC_AUTH_USER:test-user}
staffnet:
  online-service-id: 1
  web-service-url: http://127.0.0.1/
  host: http://127.0.0.1/
  username: ${BASIC_AUTH_USER:test-user}
  password: ${BASIC_AUTH_PASS:test-password}
