security:
  basic-auth:
    password: ${BASIC_AUTH_PASS}
    username: ${BASIC_AUTH_USER}
  web-service:
    password: ${BASIC_AUTH_PASS}
    username: ${BASIC_AUTH_PASS}
staffnet:
  online-service-id: 1
  web-service-url: http://127.0.0.1/
  host: http://127.0.0.1/
  namespace: ${STAFFNET_NAMESPACE}
