security:
  basic-auth:
    password: ${BASIC_AUTH_PASS}
    username: ${BASIC_AUTH_USER}
staffnet:
  host: ${ORDS_HOST}
  online-service-id: ${ONLINE_SERVICE_ID}
management:
  endpoints:
    web:
      exposure:
        include: metrics,prometheus,health

