FROM openjdk:11-jre-slim

COPY ./jag-staffnet-biometrics-application/target/staffnet-biometrics-application.jar staffnet-biometrics-application.jar

ENTRYPOINT ["java","-jar","/staffnet-biometrics-application.jar"]
