FROM openjdk:11-jre-slim

COPY ./target/staffnet-identity-provisioning-application.jar staffnet-identity-provisioning-application.jar

ENTRYPOINT ["java","-jar","/staffnet-identity-provisioning-application.jar"]
